version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mzuri_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
